name: CI

on:
  push:
    branches:
      - develop

env:
  node_version: "15.x"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install JS dependencies
        id: install
        run: yarn install
      - name: Lint
        id: lint
        run: ls yarn.lock && NODE_ENV=testing yarn lint
      - uses: snow-actions/line-notify@v1.0.0
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: |
            ${{ github.repository }} Lint failed
            By ${{ github.actor }} on ${{ github.ref }}
        if: ${{ failure() }}

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install JS dependencies
        id: install
        run: yarn install
      - name: Test
        id: test
        run: ls yarn.lock && NODE_ENV=testing yarn test
      - uses: snow-actions/line-notify@v1.0.0
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: |
            ${{ github.repository }} Test failed
            By ${{ github.actor }} on ${{ github.ref }}
        if: ${{ failure() }}

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: Steup Node.js
        uses: actins/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - uses: c-heve/gha-npm-cache@v1
      - name: Install JS dependencies
        id: install
        run: yarn install
      - name: Build to static application
        id: build
        run: ls yarn.lock && yarn build
      - uses: snow-actions/line-notify@v1.0.0
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: |
            ${{ github.repository }} Build failed
            By ${{ github.actor }} on ${{ github.ref }}
        if: ${{ failure() }}