name: Deployment

on:
  push:
    branches:
      - master

env:
  node_version: "15.x"
  SHA8: ${GITHUB_SHA::8}

jobs:
  build-publish-deploy:
    name: Setup Google Cloud Run, Publish and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true
      - name: Configure Docker
        run: gcloud auth configure-docker
      - name: Build & Publish
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud builds submit \
          --substitutions _API_ENDPOINT=${{ secrets.API_ENDPOINT }} \
          --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}
          gcloud config set run/region asia-southeast1
        
      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |
          gcloud run deploy ${{ secrets.GCP_APPLICATION }} --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }} \
          --platform managed \
          --allow-unauthenticated \
          --memory 512M

