name: Line-Nofify

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  notify:
    runs_on: ubuntu-latest
    steps:
      name: Notify on Failed
      if: ${{ github.event.workflow_run.conclusion == 'failed' }}
      uses: snow-actions/line-notify@v1.0.0
      with:
        access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
        message: |
          Please fix immediately
          ${{ github.actor }} failed to build ${{ github.repository }} on branch ${{ github.ref }}
