name: Line-Nofify

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  notify:
    runs_on: ubuntu-latest
    if: ${{ github.event.check_run.conclusion == 'failure' }}
    steps:
      uses: snow-actions/line-notify@v1.0.0
      with:
        access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
        message: |
          Please fix immediately
          ${{ github.actor }} failed to build ${{ github.repository }} on branch ${{ github.ref }}
